Server:
  port: 7911

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gdy_demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 980518

redis:
  host: localhost
  port: 6379
  max-wait: 30000
  max-active: 100
  max-idle: 20
  min-idle: 0
  timeout: 3000

mybatis:
  mapper-locations: classpath:/mapper/*.xml